version: "3.9"

services:
    container1:
        build: ./container1/apache
        container_name: container1
        ports:
            - "58464:80"
        restart: always
        networks:
            - apache-mariadb
            - one-two
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: 128M
        depends_on:
            - container1-db

    container1-db:
        build: ./container1/mysql
        container_name: container1-db
        restart: always
        networks:
            - apache-mariadb
        environment:
            MARIADB_ROOT_PASSWORD: somehorriblylongpasswordthatcannotbebruteforcedorcracked
            MARIADB_USER: sqldev
            MARIADB_PASSWORD: Php=p@in
            MARIADB_DATABASE: 2204_for_fun
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: 128M

    container2:
        build: ./container2
        container_name: container2
        networks:
            - one-two
            - two-three
        read_only: true
        tmpfs:
            - /tmp:exec
            - /run/openrc
        ulimits:
            nproc: 1024
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: 128M
                    pids: 32
            restart_policy:
                condition: on-failure
                max_attempts: 5
                delay: 3s
        cap_drop:
            - ALL
        cap_add:
            - cap_setuid
            - cap_setgid
            - cap_net_raw
            - cap_sys_chroot

    container3:
        build: ./container3
        container_name: container3
        networks:
            - two-three
        read_only: true
        tmpfs:
            - /tmp:exec
        ulimits:
            nproc: 1024
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: 128M
                    pids: 32
            restart_policy:
                condition: on-failure
                max_attempts: 5
                delay: 3s
        cap_drop:
            - ALL
        cap_add:
            - cap_dac_read_search

networks:
    apache-mariadb:
        name: container_php_mariadb_local
    one-two:
        name: container_one_two_local
        ipam:
            config:
                - subnet: 10.0.1.0/24
    two-three:
        name: container_two_three_local
        ipam:
            config:
                - subnet: 10.0.2.0/24
