version: "3.9"

services:
    # container1:
    #     build: ./container1
    #     container_name: container1
    #     ports:
    #         - "8080:8080"
    #     restart: always
    #     networks:
    #         - one-two

    container2:
        build: ./container2
        container_name: container2
        restart: always
        networks:
            - one-two
            - two-three

    container3:
        build: ./container3
        container_name: container3
        restart: always
        networks:
            - two-three

networks:
    one-two:
        name: container_one_two_local
        ipam:
            config:
                - subnet: 10.0.1.0/24
    two-three:
        name: container_two_three_local
        ipam:
            config:
                - subnet: 10.0.2.0/24
