version: "3.9"

services:
    # container1:
    #     build: ./container1/apache
    #     container_name: container1
    #     ports:
    #         - "8888:80"
    #     restart: always
    #     networks:
    #         - apache-mariadb
    #         - one-two
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: "0.3"
    #                 memory: 128M
    #
    # container1-db:
    #     build: ./container1/mysql
    #     container_name: container1-db
    #     restart: always
    #     networks:
    #         - apache-mariadb
    #     environment:
    #         MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    #         MARIADB_USER: sqldev
    #         MARIADB_PASSWORD: Php=p@in
    #         MARIADB_DATABASE: 2204_for_fun
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: "0.3"
    #                 memory: 128M

    container2:
        build: ./container2
        container_name: container2
        restart: always
        networks:
            - one-two
            - two-three
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: 128M

    container3:
        build: ./container3
        container_name: container3
        restart: always
        networks:
            - two-three
        deploy:
            resources:
                limits:
                    cpus: "0.2"
                    memory: 64M

networks:
    apache-mariadb:
        name: container_php_mariadb_local
    one-two:
        name: container_one_two_local
        ipam:
            config:
                - subnet: 10.0.1.0/24
    two-three:
        name: container_two_three_local
        ipam:
            config:
                - subnet: 10.0.2.0/24
